### Todo一覧取得
GET http://localhost:3000/todos


### Todo作成
POST http://localhost:3000/todos
Content-Type:  application/json

{
  "content": "筋トレ",
  "status": "TODAY"
}

### Todo複製
POST http://localhost:3000/todos/5678/duplicate

### 完了・未完了の切り替え
PUT http://localhost:3000/todos/2/toggle

### Todo並び替え
PUT http://localhost:3000/todos/order

### Todo内容更新
PUT http://localhost:3000/todos/12345

### Todo削除
DELETE  http://localhost:3000/todos/1