import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export const todo = async () => {
  await prisma.todo.createMany({
    data: [
      {
        id: 1,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'TODAY',
        done: false,
        content: '犬の散歩',
      },
      {
        id: 2,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'TODAY',
        done: false,
        content: '畑の水やり',
      },
      {
        id: 3,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'TODAY',
        done: false,
        content: '猪の罠回収',
      },
      {
        id: 4,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'TODAY',
        done: false,
        content: '土間のDIY',
      },
      {
        id: 5,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'TOMORROW',
        done: false,
        content: 'タンクのお掃除',
      },
      {
        id: 6,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'TOMORROW',
        done: false,
        content: '北の国から録画',
      },
      {
        id: 7,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'TOMORROW',
        done: false,
        content: 'サーフィンの練習',
      },
      {
        id: 8,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'TOMORROW',
        done: false,
        content: '自己啓発本の読破',
      },
      {
        id: 9,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'NEXT',
        done: false,
        content: 'クッキーのチョコチップ',
      },
      {
        id: 10,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'NEXT',
        done: false,
        content: '壊れかけのレディオ',
      },
      {
        id: 11,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'NEXT',
        done: false,
        content: 'マウスが壊れた',
      },
      {
        id: 12,
        uid: '5tHcvHXVTradwkofKQXPnq0VU0r0',
        status: 'NEXT',
        done: false,
        content: 'ランニング',
      },
      {
        id: 13,
        uid: 'TradwkofKQXPnq0VU0r5tHcvHXV3',
        status: 'TODAY',
        done: false,
        content: 'ランニング',
        createdAt: '2020-06-01T00:00:00.000Z',
        updatedAt: '2020-06-01T00:00:00.000Z',
      },
      {
        id: 14,
        uid: 'TradwkofKQXPnq0VU0r5tHcvHXV3',
        status: 'TOMORROW',
        done: false,
        content: 'プログラミング学習',
        createdAt: '2020-06-01T00:00:00.000Z',
        updatedAt: '2020-06-01T00:00:00.000Z',
      },
      {
        id: 15,
        uid: 'TradwkofKQXPnq0VU0r5tHcvHXV3',
        status: 'NEXT',
        done: false,
        content: 'テスト勉強',
        createdAt: '2020-06-01T00:00:00.000Z',
        updatedAt: '2020-06-01T00:00:00.000Z',
      },
    ],
  });
};
